In [1]:
import starepandas

In [2]:
ssmis = starepandas.io.granules.SSMIS(file_path='../tests/data/granules/1C.F16.SSMIS.XCAL2016-V.20210110-S002714-E020909.088907.V05A.HDF5',
                                      scans=['S1'])

In [3]:
ssmis.read_data()
ssmis.read_sidecar_index()
ssmis.read_timestamps()
ssmis.read_sidecar_latlon()

In [4]:
ssmis.to_df()['S1']

,lat,lon,sids,timestamp,Tc1,Tc2,Tc3
0,-72.609177,-41.255402,2299437706637111721,2021-01-10 00:27:16.000461,244.339996,220.759995,239.759995
1,-72.648590,-42.054047,2299435211084507593,2021-01-10 00:27:16.000461,243.830002,219.690002,239.070007
2,-72.691429,-42.852509,2299566194809236969,2021-01-10 00:27:16.000461,242.449997,218.070007,237.139999
3,-72.737686,-43.650818,2299568020253779529,2021-01-10 00:27:16.000461,241.389999,214.960007,236.860001
4,-72.787354,-44.448883,2299635836234516649,2021-01-10 00:27:16.000461,241.869995,215.949997,237.960007
...,...,...,...,...,...,...,...
289885,-86.040787,-130.470047,2284328777475425993,2021-01-10 02:09:10.000288,224.220001,199.210007,222.589996
289886,-86.277878,-130.970520,2284136116995049001,2021-01-10 02:09:10.000288,219.339996,188.729996,217.100006
289887,-86.515533,-131.431442,2284137931351340937,2021-01-10 02:09:10.000288,215.830002,181.050003,215.320007
289888,-86.753708,-131.844009,2284147551937067273,2021-01-10 02:09:10.000288,213.509995,178.589996,213.570007
289889,-86.992317,-132.196808,2284115567354799209,2021-01-10 02:09:10.000288,213.440002,178.649994,212.820007

In [4]:
ssmis.ts_start

'2021-01-10T00:27:14.800Z'